export enum ButtonType {
    Digit0 = 'digit_0',
    Digit1 = 'digit_1',
    Digit2 = 'digit_2',
    Digit3 = 'digit_3',
    Digit4 = 'digit_4',
    Digit5 = 'digit_5',
    Digit6 = 'digit_6',
    Digit7 = 'digit_7',
    Digit8 = 'digit_8',
    Digit9 = 'digit_9',
    DecimalPoint = 'decimal_point',
    Add ='add',
    Subtract = 'subtract',
    Multiply = 'multiply',
    Divide = 'divide',
    Exponent = 'exponent',
    MemoryRestore = 'memory_restore',
    MemorySave = 'memory_save',
    Clear = 'clear',
    Execute = 'execute',
}

export enum ButtonCategory {
    Digit = 'digit',
    Operation = 'operation',
    Memory = 'memory',
    Clear = 'clear',
    Execute = 'execute',
}
